Repository GSG-G13/nasa-api, pull requests merged in 2023-03, with the labels that each got.

#2 file-structure
  index.html
  js/dom.js
  js/main.js
  style/style.css
Labels: documentation

#8 add main.js
  js/main.js
Labels: done

#14 edit readme
  README.md
Labels: done

#21 edit imgs paths
  index.html
  style/style.css
Labels: done

#22 refactor js files
  js/dom.js
  js/main.js
Labels: waiting review, done
